import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#022036',
    flex: 1,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 700,
  },
  circuloam: {
    position: 'absolute',
    width: 300,
    height: 300,
    left: 200,
    top: -50,
  },
  segundocirculo: {
    position: 'absolute',
    width: 300,
    height: 300,
    right: 200,
    bottom: -50,
  },
  caixalogin: {
    backgroundColor: '#022036',
    borderRadius: 15,
    borderWidth: 5,
    borderColor: '#FFCD1B',
    width: '95%',
    maxWidth: 350,
    paddingTop: 20,
    paddingBottom: 30,
    alignItems: 'center',
    zIndex: 1,
  },
  textocampo: {
    color: '#FFCD1B',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  input: {
    backgroundColor: '#022036',
    width: '100%',
    marginBottom: 20,
    color: '#fff',
    fontSize: 14,
    borderRadius: 7,
    paddingHorizontal: 10,
    borderWidth: 2,
    borderColor: '#fff',
    height: 40,
  },
  title: {
    color: '#FFCD1B',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  form: {
    alignItems: "flex-start",
    width: '90%',
    marginBottom: 10,
  },
  buttonPriva: {
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 2,
  },
  button: {
    backgroundColor: '#F2A51A',
    width: '60%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginTop: 10,
  },
  termoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    paddingRight: 10,
  },
  checkBoxContainer: {
    backgroundColor: "transparent",
    margin: 0,
    padding: 0,
    marginLeft: -10,
  },
  termoText: {
    color: "#fff",
    fontSize: 13,
    flexShrink: 1,
  },
  termoButtonWrapper: {
    alignItems: "center",
    marginBottom: 10,
  },
  buttonPrivaText: {
    fontWeight: "bold",
  },
  buttonPrivaEnabled: {
    backgroundColor: "#F2A51A",
    borderColor: "#F2A51A",
  },
  buttonPrivaDisabled: {
    backgroundColor: "#022036",
    borderColor: "#888888",
  },
  buttonPrivaTextEnabled: {
    color: "#fff",
  },
  buttonPrivaTextDisabled: {
    color: "#888888",
  },
  inputPassword: {
    backgroundColor: '#022036',
    color: '#fff',
    fontSize: 14,
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingRight: 40,
    borderWidth: 2,
    borderColor: '#fff',
    height: 40,
    width: '100%',
  },
  eyeButton: {
    position: 'absolute',
    right: 5,
    top: 5,
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  passwordContainer: {
    position: 'relative',
    width: '100%',
    marginBottom: 15,
  },
});

export default styles;